#ifndef ERROR_H
#define ERROR_H

/**
 * @enum cgrad_error
 * @brief Enumeration of possible error codes.
 */
typedef enum
{
    NO_ERROR = 0,                /**< Operation was successful. */

    // Tensor errors
    TENSOR_NULL,                 /**< Tensor pointer is null. */
    TENSOR_GRAD_NULL,
    TENSOR_WRONG_SHAPE,          /**< Tensor has an incorrect shape. */
    TENSOR_DATA_NULL,            /**< Tensor data pointer is null. */
    TENSOR_INDEX_OUT_OF_BOUNDS,  /**< Index is out of bounds for the tensor. */
    TENSOR_SHAPE_MISMATCH,       /**< Shapes of tensors do not match. */
    TENSOR_DATA_SIZE_MISMATCH,    /**< Data sizes of tensors do not match. */
    TENSOR_INVALID_DTYPE,
    TENSOR_DTYPE_MISMATCH,
    TENSOR_ALLOCATION_FAILED,

    OPERATION_INVALID_TENSOR_DTYPE,

    // Model errors
    MODEL_MAX_PARAMS_EXCEEDED,
    MODEL_PARAMS_NULL,

    // Optimizers
    OPTIMIZER_NULL,

    // Allocator
    ALLOCATORS_NULL,
    TENSOR_ALLOCATOR_NULL,
    TENSOR_POOL_ALLOCATION_FAILED,
    COMPUTATIONAL_GRAPH_ALLOCATOR_NULL,
    COMPUTATIONAL_GRAPH_POOL_ALLOCATION_FAILED,

    // Autograd errors
    AUTOGRAD_MAX_PARENTS_EXCEEDED,
    AUTOGRAD_MAX_CHILDREN_EXCEEDED,
    AUTOGRAD_MAX_TARGETS_EXCEEDED,
    AUTOGRAD_INVALID_CONTEXT_ID,
    AUTOGRAD_CONTEXT_ID_ALREADY_TAKEN,
    AUTOGRAD_COMPUTATIONAL_GRAPH_NODE_ALLOCATION_ERROR,
    AUTOGRAD_BACKPROPAGATION_CONTEXT_NULL,
    AUTOGRAD_BACKPROPAGATION_CONTEXT_OPERAND_NULL,

    AUTOGRAD_BACKPROPAGATION_FUNCTION_NULL,
    AUTOGRAD_BACKPROPAGATION_QUEUE_NULL,
    AUTOGRAD_BACKPROPAGATION_QUEUE_FULL,
    AUTOGRAD_BACKPROPAGATION_QUEUE_EMPTY,

    AUTOGRAD_BACKPROPAGATION_TARGET_NULL,
    AUTOGRAD_BACKPROPAGATION_TARGET_COMP_GRAPH_NODE_NULL,

    AUTOGRAD_BACKPROPAGATION_ALLOCATION_FAILED,
    AUTOGRAD_BACKPROPAGATION_INVALID_TENSOR_DTYPE,
    AUTOGRAD_BACKPROPAGATION_TENSOR_NULL,

    // Datastructures
    TENSOR_LIST_NULL,
    TENSOR_LIST_FULL,

    // Dataset
    DATASET_NULL,
    DATASET_FILE_ERROR,
    CSV_DATASET_FORMAT_ERROR,
    CSV_DATASET_DATA_NULL,

    // Permutation
    INDEXES_PERMUTATION_NULL,

    // Reshape
    TENSOR_RESHAPE_INVALID_SHAPE,

    // Index Batch
    INDEXES_BATCH_NULL,

    // Memory
    MEMORY_POOL_NULL,
    MEMORY_POOL_CHUNK_ALLOCATION_FAILED,

    // General
    INPUT_NULL,
    OUTPUT_NULL,
    INVALID_BATCH_SIZE,
    INTERMEDIATES_TENSOR_LIST_NULL,

    // Linear
    LINEAR_NULL,
    LINEAR_INVALID_DTYPE,
    LINEAR_OUT_NULL,

    // Conv2d
    CONV2D_NULL,
    CONV2D_CHANNELS_MISMATCH

} cgrad_error;

#endif
