#ifndef CONFIG_H
#define CONFIG_H

// Model
#define MODEL_MAX_PARAMS 1024

// Autograd
#define AUTOGRAD_MAX_PARENTS 32
#define AUTOGRAD_MAX_CHILDREN 32
#define AUTOGRAD_MAX_TARGETS 1024
#define AUTOGRAD_MAX_BACKPROPAGATION_FUNCTION_CONTEXT_SIZE 8

// Dataset
#define DATASET_CSV_MAX_LINE_CHAR_LENGTH 8192

#endif